### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by kuncgregor** [urluur/ne_krznu#16]
Ko prideš do točke ko si poražen se ne vrneš na začetni menu in se igra zapre. Se pravi ko izgubiš vsa življenja se igra zapre.

**Comment by urluur** [comment]
Lahko bi rekli da to ni napaka, ker nikoli nisem imel namena vrniti nazaj v menu po neuspešno končani igri. Navodila so bila "igra se konča pred koncem, če ..." zato sem mislil, da se more program zapreti, ko izgubimo vsa življenja. Nekako tako so se obnašale tudi nekatere stare igre iz časov windows 98.

**Comment by kuncgregor** [comment]
Aha rezumem ja. Čeprav bi bil vesel če bi bilo možnost, saj ne pridem čez 2. nivo igre. Rad bi pa prišel do Doom dela.
Upam da se da kaj narediti, da ne bo potrebo vsakič znova zagnati igro kot administrator, saj to uniči "immersion".
(seveda ko boš imel čas)
Hvala

**Comment by urluur** [comment]
Če se ti ne da zaganjat kot administrator lahko provaš portable verzijo k ne zahteva admin pravic.. Aja pa ko že omenjaš doom del igre.. Bodi pozoren na "zanimivosti" ko se ti igra zapre in mogče boš naletel na kakšen uporaben hint.
Pa še to.. če ti je težko prist mimo drugega levela se raje izogibaj nasprotnikom potem pa pojdi na farmo pobrat tjulne ki so jih nasprotniki tja nesli. Na tak način ne boš dobil veliko točk, a usaj lažje boš prišel čez level.
Have fun :)
