### ISSUE TITLE
[Hrošč] Program se sesuje, ko te nasprotnik ubije.

### ISSUE THREAD

**Issue by kuncgregor** [urluur/ne_krznu#6]
Ko se igralec dotakne nasprotnika, se igra zapre.

Prosim popravite ta hrošč, saj bi rad normalno igral igro.

LP

**Comment by urluur** [comment]
Bi mi znal povedati še kakšne bolj podrobne informacije, naprimer ali to dela verzija v installerju, portable ali oboje?

**Comment by kuncgregor** [comment]
V installer verziji!
Nisem probal še portable.

**Comment by urluur** [comment]
Problem je bil omenjen ze na [strani za namestitev](https://github.com/urluur/ne_krznu/releases/tag/v1.0#tag-select-menu-371bd2c2-9d5b-11eb-901c-4096312a7954:~:text=ne%20namestite%20igre%20v%20sistemske%20datoteke,savefile%20(to%20pomen%20d%20sam%20crasha).). Samo zaženi program kot administrator ali pa namesti [portable](https://github.com/urluur/ne_krznu/releases/download/v1.0/ne_krznu_urlu_1.0_installer.msi) verzijo. Bom objavil novo verzijo ko bom ta problem #11 popravil.
LpL
